export const GET_DATA = "GET_DATA";
export const POST_DATA = "POST_DATA";
export const WIZARDS = [
  "GOLONGAN",
  "ORGANISASI",
  "KESEHATAN",
  "PMK",
  "ANGKA_KREDIT",
  "P_INSTANSI",
  "PROFESI",
  "KEDUDUKAN_HUKUM",
  "DATA_PRIBADI",
  "JABATAN",
  "DIKLAT",
  "KELUARGA",
  "HUK_DISIPLIN",
  "PENDIDIKAN",
  "CTLN",
  "CPNS",
  "SKP",
  "PENGHARGAAN",
  "LHKPN",
  "LHKASN",
  "PRESTASI",
  "KEPANITIAN",
  "KGB",
  "POTENSI",
  "TUNJANGAN_KINERJA",
  "TUNJANGAN_KEMAHALAN",
  "KONTRAK_PPPK",
];
export const GET_DATA_PNS_SUCCESS = "GET_DATA_PNS_SUCCESS";
export const GET_DATA_PNS_PENDING = "GET_DATA_PNS_PENDING";
export const GET_DATA_PNS_ERROR = "GET_DATA_PNS_ERROR";

export const GET_BYID_SUCCESS = "GET_BYID_SUCCESS";
export const GET_BYID_PENDING = "GET_BYID_PENDING";
export const GET_BYID_ERROR = "GET_BYID_ERROR";

export const GET_NAME_SUCCESS = "GET_NAME_SUCCESS";
export const GET_NAME_PENDING = "GET_NAME_PENDING";
export const GET_NAME_ERROR = "GET_NAME_ERROR";

export const GET_LIST_USULAN_SUCCESS = "GET_LIST_USULAN_SUCCESS";
export const GET_LIST_USULAN_PENDING = "GET_LIST_USULAN_PENDING";
export const GET_LIST_USULAN_ERROR = "GET_LIST_USULAN_ERROR";

export const GET_DATA_ID_SUCCESS = "GET_DATA_ID_SUCCESS";
export const GET_DATA_ID_PENDING = "GET_DATA_ID_PENDING";
export const GET_DATA_ID_ERROR = "GET_DATA_ID_ERROR";

export const GET_ASN_SUCCESS = "GET_ASN_SUCCESS";
export const GET_ASN_PENDING = "GET_ASN_PENDING";
export const GET_ASN_ERROR = "GET_ASN_ERROR";

export const GET_NAME_ASN_SUCCESS = "GET_NAME_ASN_SUCCESS";
export const GET_NAME_ASN_PENDING = "GET_NAME_ASN_PENDING";
export const GET_NAME_ASN_ERROR = "GET_NAME_ASN_ERROR";

export const COBAIN = "COBAIN";
export const COBAIN_PENDING = "COBAIN_PENDING";

export const POST_USULAN_PNS_SUCCESS = "POST_USULAN_PNS_SUCCESS"
export const POST_USULAN_PNS_PENDING = "POST_USULAN_PNS_PENDING"
export const POST_USULAN_PNS_ERROR = "POST_USULAN_PNS_ERROR"

export const EDIT_USULAN_PNS_SUCCESS = "EDIT_USULAN_PNS_SUCCESS"
export const EDIT_USULAN_PNS_PENDING = "EDIT_USULAN_PNS_PENDING"
export const EDIT_USULAN_PNS_ERROR = "EDIT_USULAN_PNS_ERROR"

export const UPLOAD_DOKUMEN_PNS_SUCCESS = "UPLOAD_DOKUMEN_PNS_SUCCESS"
export const UPLOAD_DOKUMEN_PNS_ERROR = "UPLOAD_DOKUMEN_PNS_ERROR"
export const UPLOAD_DOKUMEN_PNS_PENDING = "UPLOAD_DOKUMEN_PNS_PENDING"

export const GET_GOLONGAN_PNS_SUCCESS = "GET_GOLONGAN_PNS_SUCCESS"
export const GET_GOLONGAN_PNS_PENDING = "GET_GOLONGAN_PNS_PENDING"
export const GET_GOLONGAN_PNS_ERROR = "GET_GOLONGAN_PNS_ERROR"

export const POST_USULAN_NEW_SUCCESS = "POST_USULAN_NEW_SUCCESS"
export const POST_USULAN_NEW_PENDING = "POST_USULAN_NEW_PENDING"
export const POST_USULAN_NEW_ERROR = "POST_USULAN_NEW_ERROR"

export const GET_REF_GOLONGAN_SUCCESS = "GET_REF_GOLONGAN_SUCCESS"
export const GET_REF_GOLONGAN_PENDING = "GET_REF_GOLONGAN_PENDING"
export const GET_REF_GOLONGAN_ERROR = "GET_REF_GOLONGAN_ERROR"

export const GET_REF_KP_SUCCESS = "GET_REF_KP_SUCCESS"
export const GET_REF_KP_PENDING = "GET_REF_KP_PENDING"
export const GET_REF_KP_ERROR = "GET_REF_KP_ERROR"